[package]
name = "asm-checksums"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
sha2 = "0.10.8"
static-env = { path = "../static-env" }

[dev-dependencies]
pretty_assertions = "1.4.0"
